auth_server:
  # Public dummy UAA for local development usage only!
  # Username/password: credhub/password
  url: https://34.206.233.195:8443


security:
  oauth2:
    enabled: true
    resource:
      jwt:
        key_value: |
          -----BEGIN PUBLIC KEY-----
          MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAo9hvZNbP3U9Ory1aTHt7
          OXucx2Ur0mhyrzKeB1T9R3gLuUCYXBUuc2PhhoQ5aKP+ii3UsWVx0WUsdLmX+8x2
          iHDZ20ZCCg9MrOgAhVDsGGx3eNjNRdbk3RaeDJlI4RD1cy8+cMza2dp7h2Yk8Um6
          U/+vXDBIdsKAQZayrm4X1xIc27D78KPSZeP3ux2qV7y4j5CHLjhg5mxnfWpJxltD
          G1YtacCIbL3H41NVboqerJopZbtGAGh6/60GriUqf1z82TVaovOUp/HfGLF3OK8G
          BYbcCW+Z3N1Q4QFKiNcNjWZNViKGAysdhogp/P6xb8cFFksiKFOi6HyWEW8/wr8w
          CwIDAQAB
          -----END PUBLIC KEY-----
